//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Экзамен
{
    using System;
    using System.Collections.Generic;
    
    public partial class Individuals
    {
        public int id { get; set; }
        public string INN { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public Nullable<int> idManager { get; set; }
    
        public virtual Manager Manager { get; set; }
    }
}
