//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Экзамен
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ЭкзаменEntities : DbContext
    {
        public ЭкзаменEntities()
            : base("name=ЭкзаменEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Individuals> Individuals { get; set; }
        public virtual DbSet<LegalEntities> LegalEntities { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
